#!/bin/bash
set -e

IMAGE=sherdock-ui

cd $(dirname $0)/..
docker build -t $IMAGE -f Dockerfile.ui .
docker run -u $(id -u) -v $(pwd):/target $IMAGE cp /go/src/github.com/rancher/sherdock/bindata_assetfs.go /target
