#!/bin/bash
set -e

IMAGE=rancherio/sherdock
BUILD=${IMAGE}-build

cd $(dirname $0)/..

./script/build-ui

docker build -t $BUILD .
docker run -u $(id -u) -v $(pwd):/target $BUILD cp /usr/bin/sherdock /target
docker build -t $IMAGE -f Dockerfile.dist .
